/**
 * This file was automatically generated by scripts/generate-types.ts.
 */

/**
 * A sequence of questions
 *
 * @maxItems 25
 */
export type Questions = {
  question: string
  /**
   * @maxItems 10
   */
  topics: string[]
  answerType: 'singleChoice' | 'multipleChoice' | 'text'
  /**
   * @maxItems 10
   */
  answers: {
    answer: string
    isCorrect: boolean
  }[]
  shouldShuffle: boolean
}[]

export interface Quizzes {
  /**
   * Format: bigint
   * @description Note:
   * This is a Primary Key.<pk/>
   */
  id: number
  /** Format: text */
  title: string
  /** Format: uuid */
  creator_id: string
  /**
   * Format: boolean
   * @default false
   */
  is_published: boolean
  /**
   * Format: timestamp with time zone
   * @default timezone('utc'::text, now())
   */
  inserted_at: string
  /**
   * Format: timestamp with time zone
   * @default timezone('utc'::text, now())
   */
  updated_at: string
  /**
   * Format: tsvector
   * @default to_tsvector('english'::regconfig, title)
   */
  fts?: string
  questions: Questions
}
