/**
 * This file was automatically generated by scripts/generate-types.ts.
 */
import { Questions } from './questions.generated'

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[]

export interface Database {
  public: {
    Tables: {
      quizzes: {
        Row: {
          creator_id: string
          fts: unknown | null
          id: number
          inserted_at: string
          is_published: boolean
          questions: Questions
          title: string
          updated_at: string
        }
        Insert: {
          creator_id: string
          fts?: unknown | null
          id?: number
          inserted_at?: string
          is_published?: boolean
          questions?: Questions
          title: string
          updated_at?: string
        }
        Update: {
          creator_id?: string
          fts?: unknown | null
          id?: number
          inserted_at?: string
          is_published?: boolean
          questions?: Questions
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'quizzes_creator_id_fkey'
            columns: ['creator_id']
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
