/**
 * This file was automatically generated by scripts/generate-types.ts.
 */

/**
 * A sequence of questions
 *
 * @maxItems 25
 */
export type Questions = {
  question: string
  /**
   * @maxItems 10
   */
  topics: string[]
  answerType: 'singleChoice' | 'multipleChoice' | 'text'
  /**
   * @maxItems 10
   */
  answers: {
    answer: string
    isCorrect: boolean
  }[]
  shouldShuffle: boolean
}[]
